### ISSUE TITLE
Create illustration for Lepidopter

### ISSUE THREAD

**Issue by agrabeli** [ooni/design-system#10]
The illustration for Lepidopter could include the official Raspberry Pi raspberry (featured here: https://ooni.torproject.org/install/) with the OONI octopus rapped around it from behind the raspberry. That way, you would see the octopus head sticking out from the left side of the raspberry, and its four tentacles rapped around the raspberry (two tentacles on each side).

Thoughts?

**Comment by elioqoshi** [comment]
I suppose we are not moving forward with this (what's the status on Lepidopter anyway?). Feel free to reopen if needed.
