### ISSUE TITLE
Create Powered by OONI banner

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#15]
We should have a horizontal (and vertical?) banner for people to say that their project or website is using OONI data.

I think the copy on the banner could say "Powered by OONI". An example of a banner of this sort is the "Powered by Google" one: https://developers.google.com/places/web-service/policies.

**Comment by elioqoshi** [comment]
I kept the OONI icon mark in here to be sure. I suppose we can use both monochrome and color versions for different use cases. Feedback welcome:

![image](https://user-images.githubusercontent.com/5436686/33556969-121b65a4-d906-11e7-9438-a3ad3d94dab6.png)

**Comment by elioqoshi** [comment]
This might be more fitting. Regular weight and a bit bigger font size

![image](https://user-images.githubusercontent.com/5436686/33557045-590e2582-d906-11e7-81bd-d4550c1f9cd9.png)
