### ISSUE TITLE
Clean up and finalise the citizenlab icon set

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#16]
I started making these here: https://github.com/citizenlab/test-lists/issues/202.

What needs to happen to make these ready for use is:

* [x] Consider if we should make some adjustments to some icons to make them more consistent
* [x] Export every individual icon as an SVG and add them to this repo
* [x] Create react components wrapping each icon

**Comment by hellais** [comment]
Here is a zip that contains the svg and sketch source of them:

[CitizenLab category codes.zip](https://github.com/OpenObservatory/design/files/1524814/CitizenLab.category.codes.zip)

**Comment by elioqoshi** [comment]
I went over these today and yesterday and revamped almost every icon. I think the results are satisfying right now. I added a bit of OONI flair for consistency by rounding the icons a bit where needed.

If this is good to go, I will go on with export:

![image](https://user-images.githubusercontent.com/5436686/33555192-b50593c2-d8ff-11e7-9d67-c1cd045c3317.png)


cc @hellais @agrabeli @bassosimone

**Comment by elioqoshi** [comment]
Going ahead with exporting these (red is margin for all icons)

![image](https://user-images.githubusercontent.com/5436686/33558908-6cdab97c-d90b-11e7-9c90-b16ed4230789.png)

![image](https://user-images.githubusercontent.com/5436686/33558945-91e5f024-d90b-11e7-8da6-ef1bd7661c52.png)

**Comment by elioqoshi** [comment]
Done.

Pull Request here @hellais 
https://github.com/OpenObservatory/design/pull/18

**Comment by hellais** [comment]
Let's close tickets only when the PR is merged and reviewed

**Comment by hellais** [comment]
Also we haven't yet created React wrappers around them, yet.

**Comment by elioqoshi** [comment]
Anything blocked from my side here?

**Comment by hellais** [comment]
This is implemented in https://github.com/ooni/design-system/commit/798880d2078be8e50738367d32acb5f32256d8be
