### ISSUE TITLE
Export assets for brand guidelines

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#17]
Currently the `design/brand` page is missing various image assets. They should be exported from the pdf and placed in the appropriate source tree to show up in the brand page.

What is currently missing is:

* [ ] Minimum spacing
* [ ] Sub brands
* [ ] Logo don'ts

**Comment by hellais** [comment]
This should happen inside of the design.ooni.io repo and how to do it is:

0. Create a branch from master of https://github.com/ooni/design.ooni.io
1. Upload the svg to: https://github.com/ooni/design.ooni.io/tree/master/static/images
2. Edit https://github.com/ooni/design.ooni.io/blob/master/md/brand.md to point to the image location
3. Open a PR

**Comment by elioqoshi** [comment]
@hellais I'd prefer working on this once there are no other more pressing projects and where I can dedicate some time to the style guide altogether. Would that make sense?

**Comment by elioqoshi** [comment]
@hellais this should be good to go. I set up GitHub Desktop in the meantime. PR: https://github.com/ooni/design.ooni.io/pull/2

**Comment by hellais** [comment]
@elioqoshi the files are still missing. See: https://github.com/ooni/design.ooni.io/pull/2#issuecomment-408816857

**Comment by hellais** [comment]
Merged.
