### ISSUE TITLE
OONI Master Style Guide

### ISSUE THREAD

**Issue by elioqoshi** [ooni/design-system#3]
Hey folks,

Following the Data Viz Style Guide Arturo drafted, we want to incorporate everything into a Master Style guide which can be used as a reference for future work. I have worked in the past week on a draft for this, based on the approach we had for the Tor style guide as well. 

As of now, this includes:

- Typography
- Colors
- Iconography
- Logos & Sub-branding

I'd like to gather your feedback here to wrap these sections up so we can move onto the other areas, such as web and mobile UI elements, data viz etc.

Feel free to ping me for anything here or on Slack

[Styleguide3.pdf](https://github.com/OpenObservatory/design/files/1259701/Styleguide3.pdf)

**Comment by hellais** [comment]
Here is some feedback.

## Minor changes/typos

* [ ] Page 2 - I should review and finalise the copy here
* [ ] Page 3 - the description of "Digital Text" says at some point "As a general rule, use a white background and text that is OONI gray or black". I think it should say "OONI blue or black" (and probably black should be before OONI blue)
* [ ] Page 3 - The code snippet example should use OONI software. For example:
```
pip install ooniprobe
ooniprobe web_connectivity --url https://ooni.torproject.org/
```
* [ ] Page 3 - In the colors section you should also list black as it's a color used in copy
* [ ] Page 3 - Our monospaced font is actually "Source Code Pro" not "Fira Mono"

## Possibly more features

* [ ] The font size, weight, style and color for various typographic elements:
    - Major Headers (`<h1>`)
    - Minor Headers (`<h2>`)
    - Content (`<p>`)
    - Hyperlinks (`<a>`)
* [ ] Typographic scaling of fonts with focus on being responsive (ex. a `<h1>` on a large screen can be `96px`, but on a smaller screen may become `64px`)
* [ ] What are the standards for padding of various elements in digital content
* [ ] We should mention what should be the styling for the following basic elements (at minimum) (Question: should these be different if we are talking about web vs mobile?). In general things that are important to document are: `border-radius`, `padding`, `font-size`, `colors`:
   - [ ] [Primary](http://jxnblk.com/rebass/components/Button) and [secondary buttons](http://jxnblk.com/rebass/components/ButtonOutline)
   - [ ] [Input](http://jxnblk.com/rebass/components/Input) box
   - [ ] [Select](http://jxnblk.com/rebass/components/Select) menu
   - [ ] [Textarea](http://jxnblk.com/rebass/components/Textarea) box
   - [ ] General layout of a form
   - [ ] Web banner with OONI logo and call to action (for use in our custom URI scheme)
   - This is a good list of web components: http://jxnblk.com/rebass/components
* [ ] Page background color
* [ ] Other colors are useful to be used and in which context they should be used

**Comment by hellais** [comment]
I made a PR with the live style guide here: https://github.com/OpenObservatory/design/pull/4

**Comment by hellais** [comment]
This is actually not done. I filed a relevant ticket for it here: https://github.com/ooni/design.ooni.io/issues/5
