### ISSUE TITLE
Fix primary and secondary brand colors

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#41]
We noticed with @elioqoshi that there was an issue with the current color scheme.

1. Our secondary (`LIGHT_BLUE`) color is no longer present inside of the color palette
2. Some icons inside of https://github.com/ooni/design-system/tree/master/components/svgs/logos contain the wrong colors for both the primary and secondary brand

In order to resolve this we are going to do the following:

* [ ] @elioqoshi will figure out why this happened and if there is some nasty illustrator option to avoid mangling the color codes
* [x] @hellais will write a script to replace `#1386C8` with `#5db8fe` (OONI_BLUE) in the icons and `#8DD5F6` and `#8DD5F7` with `#8DD5F8` (OONI_LIGHT_BLUE)
* [x] We will adjust the color palette of the `blue` grandient to have `blue2` be `#8DD5F8`

**Comment by elioqoshi** [comment]
I am looking at this today.

**Comment by elioqoshi** [comment]
I checked the source master file for the logos and the color codes were correct. It seems they were exported correctly from Illustrator. However I seemed to have done some color conversion error in the Do's and Don'ts SVG's. I am checking them now and adjusting the gradient in the design system.

**Comment by hellais** [comment]
> I checked the source master file for the logos and the color codes were correct. It seems they were exported correctly from Illustrator.

How is that possible? Are these not the same files that were uploaded to github in: https://github.com/ooni/design-system/pull/12/files and contain the misaligned colors?

**Comment by elioqoshi** [comment]
Eventually not. Locally they are fine. I will double check on the next occasion I need to export but it I don't think it's worth troubleshooting this more.

**Comment by hellais** [comment]
Ok, that's odd. Anyways let's move on and maybe it good to double check the colors the next times and see if there is some oddity of this sorts happening.

Doing a very quick search I came across some possible causes for it:
* https://graphicdesign.stackexchange.com/questions/67610/illustrator-cs6-changes-colours-when-saving-as-png-or-svg
* https://forums.adobe.com/thread/2240725

Anyways I am closing this and merging #42.
