### ISSUE TITLE
Export Link component to style links uniformly

### ISSUE THREAD

**Issue by sarathms** [ooni/design-system#51]
Currently, `<Link>` is directly exported from `rebass@v2.x.x` which defaults to `color: 'blue'`. This needs to be changed to `theme.colors.blue7`

**Comment by sarathms** [comment]
This was done in 4928d4da94d695673bbce7bd721aeeab4ffe63f5. 

@hellais I don't remember why we wanted to default it to `blue7`, but right now it is `blue5`. Do we have a guideline for link styling yet?

**Comment by hellais** [comment]
> Do we have a guideline for link styling yet

We don't have such a guide. I am now thinking that maybe a reason not to use blue5, is that blue5 is also OONI Blue and it may not be a good idea to use it for links.

Where did you find that we wanted to use `blue7`? In my opinion `blue7` is a bit too dark and I would suggest instead using `blue6`.

**Comment by sarathms** [comment]
> Where did you find that we wanted to use blue7
In the opening post of this issue.

> I would suggest instead using blue6
Lets close this issue and open a new one to for this change.
