### ISSUE TITLE
Upgrade to rebass 3

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#56]
It seems like there are new versions of rebass and styled-system.

cc @sarathms

**Comment by camilaavilarinho** [comment]
Hi, can I work on this one?

**Comment by hellais** [comment]
Changed the title as we have styled-components 4 already tracked as part of: https://github.com/ooni/design-system/issues/49.

**Comment by sarathms** [comment]
This involves adding replacements to the components that rebass has stopped exporting from v3 onwards. We only use a few of them, but they need to written into the repo now.
