### ISSUE TITLE
Fix issue with fontSizeMult

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#57]
We have a warning message saying that fontSizeMult is deprecated which we should fix.

I think this should be done with https://github.com/ooni/design-system/issues/56 and we should evaluate even just using the stock rebass Button component directly or drawing inspiration from it to implement a compatible API.

It has the `variant` prop which is equivalent to our `hollow` prop.

cc @sarathms

**Comment by sarathms** [comment]
I have ported some more components to `rebass@v3` using the variant based theming approach. The [PR](https://github.com/ooni/design-system/pull/93#issuecomment-654200666) has a checklist to track progress.
