### ISSUE TITLE
Revamp OONI explorer

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#6]
I think we should make some improvements to the UI and layout of OONI explorer.

I would suggest we use this ticket to collect ideas and possible ways to do it.

As a requirement I would say we should first define the style for our web assets.

Edit: I have actually already started to build this on the side for a while now and here are some of the views:

<img width="1680" alt="screen shot 2017-09-05 at 17 58 40" src="https://user-images.githubusercontent.com/424620/30071686-ec6f2abe-9267-11e7-9dd7-b9f9657c2462.png">
<img width="1679" alt="screen shot 2017-09-05 at 17 58 28" src="https://user-images.githubusercontent.com/424620/30071685-ec6d6ea4-9267-11e7-89f5-9774e7e1499d.png">

**Comment by agrabeli** [comment]
For starters, I would suggest the following improvements:

1. Make "Filter Results" show the filters by default (I have noticed that many users don't notice that they are supposed to click on it)
2. Enable users to browse through measurements without being thrown back to the first page every time they finish reviewing a measurement

During the OONI Partner Gathering we collected some initial community feedback to revamp OONI Explorer. Notably:

1. Show top censorship findings per country
2. Explain the measurement data in an easy to understand way
3. Provide separate lists of confirmed censorship cases and of anomalous measurements (potentially including false positives) per country in OONI Explorer
4. Enable users to submit feedback via OONI Explorer on whether they can access a site or not (especially if measurements for a site have been flagged/listed as "anomalous")
5. Export data in csv files
6. Enable users to export graphs and data visualizations from OONI Explorer 

You can also find the above feedback here: https://ooni.torproject.org/post/ooni-partner-gathering-2017/#challenges-and-needs

**Comment by elioqoshi** [comment]
I like the concept of where this should go. Let's have a look at this after we have redesigned the website, which is a big deal already.

**Comment by hellais** [comment]
As discussed with @elioqoshi we should focus on OONI Explorer before the website as we are aiming to ship this by Q3

**Comment by hellais** [comment]
Here is a mockup I made for the country page:

<img width="681" alt="screen shot 2018-01-03 at 13 53 51" src="https://user-images.githubusercontent.com/424620/34521360-a447988c-f08d-11e7-9bc4-400d612096d3.png">

These are I think what are most of the pages we need.

## Top level pages

* Home/Landing Page
* Search/Explore view
* Highlights
* Country pages

### Nested pages

* IM app info
* Website info
* Speed & performance info
* Censorship Circumvention Tool info
* Middle box info
* Measurement details (when you click on an individual measurement)
* My probe (to see the list of measurements a certain user ran, this is a longer term future goal, not to be done now)

**Comment by hellais** [comment]
Closing this ticket in favour of: https://github.com/ooni/explorer/issues/2
