### ISSUE TITLE
Add fontWeight prop to Text component

### ISSUE THREAD

**Issue by sarathms** [ooni/design-system#63]
Add a `fontWeight` prop to the `Text` component. This is available [from `styled-system`](https://github.com/ooni/design-system/blob/master/components/util.js#L12). Identical in [implementation to `textAlign`](https://github.com/ooni/design-system/blob/master/components/atoms/Text.js#L18) and other such props.

**Comment by justinushermawan** [comment]
Hey, can I take this issue?

**Comment by sarathms** [comment]
Looks like its already taken.
