### ISSUE TITLE
Revamp OONI mobile apps

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#7]
Regarding the mobile apps here is some of my reasoning behind some of the areas that need improvement:

1. I think it's important to give the user an estimate of how long the test will run for (as well as how much bandwidth it will use)

2. The tests related to middle box detection are very fast and there should really be no good reason to have them be split up into multiple pages

3. It's ideal to consolidate multiple tests inside of the same logical group (like we do on desktop with decks)

4. It's not clear to users that by clicking on the test name row they get to see the details for the test and we need to show this to offer advanced options for customising the test

5. The hamburger menu/side bar panel are not so nice (possibly bike-shedding)
We also don't really have the need to have side-bar since we don't have that many menu items. Using a bottom navigation bar is a better UX solution, because:
  a. It gives the user an idea of where they are inside of the application
  b. It gives them immediately an idea of what are the functions that are possible through the app
  c. They have to click in less places to reach their destination

The bottom bar is more of an iOS thing than an Android thing, though google has recently added to material design the bottom bar, so it should be fine to use this pattern for both Android and iOS.

Here are some initial exploratory mockups I made:

## Navigational flow tree

![app-view tree](https://user-images.githubusercontent.com/424620/29960281-547713f8-8efb-11e7-9ab9-37bbe1d94942.png)

## Home

![app - home - ios](https://user-images.githubusercontent.com/424620/29960277-517f7dd4-8efb-11e7-8701-00a9448d38e9.png)

## Test details

![app - test details - both](https://user-images.githubusercontent.com/424620/29960306-6a1be1f2-8efb-11e7-8f35-eea4f61f32e7.png)

## Test settings

![app - test settings - android](https://user-images.githubusercontent.com/424620/29960311-74e3398c-8efb-11e7-9321-8db6cad2d9e9.png)

## Test settings - site categories

![app - test settings - site categories - android](https://user-images.githubusercontent.com/424620/29960323-814d4d8e-8efb-11e7-8a0e-6d45b828dee5.png)

## Test settings - custom URL

![app - test settings - custom url - android](https://user-images.githubusercontent.com/424620/29960349-9070002c-8efb-11e7-81d7-068e76380d0b.png)

## App sidebar (in case we keep it)

![app - sidebar](https://user-images.githubusercontent.com/424620/29960359-97a6c8c6-8efb-11e7-9a79-953f2bad26e9.png)

## App settings

![app settings - android](https://user-images.githubusercontent.com/424620/29960368-a3d48af2-8efb-11e7-94cf-2d5af6aa2071.png)

**Comment by hellais** [comment]
Note to future self:

* Remember to add running test screen and possibly support multiple tests

**Comment by agrabeli** [comment]
@hellais this all looks really great!

I have the following suggestions:

1. Perhaps remove "Performance" as a category and just keep "Network Neutrality"? They would both include the same tests (NDT and DASH), so I don't see a strong argument in favor of keeping the "Performance" tab (which ultimately serves as a duplicate here).

2. Happy to see that users can choose which types of sites to test! Will all of the categories be enabled by default, or as you show them in the image? 

3. I'd suggest rephrasing "Past tests" in the app to "View results", as "Past tests" can be a bit confusing.

**Comment by hellais** [comment]
@elioqoshi I made UI flow chart for the current OONI Probe Mobile app UI flow.

![ooniprobemobilecurrentuiflow](https://user-images.githubusercontent.com/424620/30993097-842f85fe-a4ad-11e7-8e44-d1ae958b5bf5.png)

I used draw.io and I will share with you the .xml file on slack

**Comment by hellais** [comment]
Here is the latest mockup: https://xd.adobe.com/view/92d654eb-8b34-409e-7f38-05b739d47bc3-e4e7/

**Comment by elioqoshi** [comment]
Also the specs (which might be also easier to have an overview of all views):
https://xd.adobe.com/spec/c6b4bb86-6c2b-412d-6bc1-5d7855697333-b085/

**Comment by elioqoshi** [comment]
Closing this as the design mockups have been finished (whatever "finished" means).
