### ISSUE TITLE
Add circumvention tool tests icon

### ISSUE THREAD

**Issue by hellais** [ooni/design-system#72]
@holantonela mentioned there is an icon for the circumvention tests already in: https://github.com/ooni/probe/issues/804#issuecomment-559800723

We should add the icon and the color to the design-system.

The icon needs to be added in SVG form in here: https://github.com/ooni/design-system/tree/master/components/svgs/icons.

**Comment by hellais** [comment]
Once we add it to the design-system, we should update OONI Explorer to have this icon too. See: https://explorer.ooni.org/measurement/20191128T145358Z_AS134056_bfSYXbbO0G5aczuNhndremCDczZCZEBgj2g3HqYwTcIGXAvtNi

**Comment by hellais** [comment]
@holantonela do you have the svg of the circumvention icon in https://xd.adobe.com/view/583a7c33-770d-4b66-7677-3c081e178609-2e0b/screen/e63b1a10-8f35-4a9f-97a2-7f45a00a6a75/Circumvention-Progress-1 handy?

**Comment by holantonela** [comment]
I think we are good here ⬇️
```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="30px" height="30px" viewBox="0 0 30 30" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>Circumvention Test</title>
     <g style="clip-path: url(#clip-path)">
        <path d="M18.0076825,14.1283019 L14,14.1283019 L14,9.6 L18.0076825,9.6 L18.0076825,6.30943396 L24,11.7433962 L18.0076825,17.1773585 L18.0076825,14.1283019 Z M0,9.6 L4.60947503,9.6 L4.60947503,14.1283019 L0,14.1283019 L0,9.6 Z M7,-2.84217094e-14 L11.609475,-2.84217094e-14 L11.609475,24 L7,24 L7,-2.84217094e-14 Z" id="Triangle-2"></path>
    </g>
</svg>
```

**Comment by sarathms** [comment]
@hellais I am not familiar with the svg inline style problem enough to spot it directly. The svg in the comment above is not the same format as all the other files like this one [from here](https://raw.githubusercontent.com/ooni/design-system/master/components/svgs/icons/NettestGroupInstantMessaging.svg).

Please confirm if this needs to be exported differently.
```
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30" height="30" viewBox="0 0 30 30">
  <defs>
    <clipPath id="clip-path">
      <rect width="30" height="30" style="fill: none"/>
    </clipPath>
  </defs>
  <title>Instant Messaging</title>
  <g style="clip-path: url(#clip-path)">
    <path d="M4.9,26.187l4.347-4.032a1.1,1.1,0,0,1,.728-.3h14.97a1.079,1.079,0,0,0,1.082-1.081V6.221a1.079,1.079,0,0,0-1.082-1.082H4.171A1.079,1.079,0,0,0,3.089,6.221V25.4A1.074,1.074,0,0,0,4.9,26.187Z"/>
  </g>
</svg>
```

**Comment by hellais** [comment]
@sarathms yes the svg provided by @holantonela is good.

For reference here is an example of a **bad** svg with inline styles: https://raw.githubusercontent.com/ooni/design-system/555aa181a2fb303bb8b6b0e9ad560436e848aa5b/components/svgs/icons/website-categories/LGBT.svg.

You can also omit some unnecessary elements when committing the svg to our repo, like so:

```
<svg width="30px" height="30px" viewBox="0 0 30 30" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
     <g>
        <path d="M18.0076825,14.1283019 L14,14.1283019 L14,9.6 L18.0076825,9.6 L18.0076825,6.30943396 L24,11.7433962 L18.0076825,17.1773585 L18.0076825,14.1283019 Z M0,9.6 L4.60947503,9.6 L4.60947503,14.1283019 L0,14.1283019 L0,9.6 Z M7,-2.84217094e-14 L11.609475,-2.84217094e-14 L11.609475,24 L7,24 L7,-2.84217094e-14 Z" id="Triangle-2"></path>
    </g>
</svg>
```
