### ISSUE TITLE
Icon for Psiphon test

### ISSUE THREAD

**Issue by sarathms** [ooni/design-system#78]
This is similar to the `WhatsApp` and `Telegram` icons we use in the probes and explorer under the `IM` group. We already have an icon for `vanilla_tor` test under the `Circumvention` group.

**Comment by sarathms** [comment]
On a related note, shouldn't we now have an icon for the new `tor` test different from that of `vanilla_tor`?

**Comment by hellais** [comment]
> shouldn't we now have an icon for the new tor test

I think that in light of the fact that `vanilla_tor` is going to become eventually a subset of the `tor` test and there will not be a `vanilla_tor` test anymore, we are fine to use the old `vanilla_tor` icon.

**Comment by sarathms** [comment]
@hellais I have attached the SVG we received from Psiphon. It needs to be tweaked because it has gradients and styles defined in the SVG. I edited it (NettestPsiphon-mono.svg) to make it use a path to represent the logo. But I couldn't export it in the right format.

Can you help fix the format?

[NettestPsiphon.zip](https://github.com/ooni/design-system/files/4046999/NettestPsiphon.zip)

**Comment by hellais** [comment]
I added this inside of: https://github.com/ooni/design-system/pull/79. The CI needs some fixing though. @sarathms can you help with the CI?

**Comment by sarathms** [comment]
Tests were updated to clear CI. PR was merged.
